export enum DATA_TEST_ID {
  HOME_PAGE = 'home-page-id',
  CONTACTS_PAGE = 'contacts-page-id',
  TIMELINE_PAGE = 'timeline-page-id',
  BANK_CARD_PAGE = 'bank-card-page-id',
  TOGGLE_THEME = 'toggle-theme',
  LOADER = 'loader',
  SELECT_CURRENCY = 'select-currency',
  INPUT_DATE = 'input-date',
  SELECT_PERIOD = 'select-period',
  BAR_CHART = 'bar-chart',
  SELECT = 'select',
  SELECT_INPUT = 'select-input',
  SELECT_LIST = 'select-list',
}
